[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "pytz>=2025.1",
    "requests>=2.32.3",
    "twilio>=9.5.0",
]
